import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";

// Components imports
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import CommunityBanner from "../../components/CommunityBanner";

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Inferatos | About</title>
      </Head>
      <Header />
      <div className="container mx-auto mt-44 mb-36 px-6">
        <div className="flex gap-16 flex-col text-left items-center">
          <h2>Terms & Conditions</h2>
          <motion.h4
            initial={{ opacity: 0, y: -10 }}
            whileInView={{
              opacity: 1,
              y: 0,
              transition: {
                duration: 0.4,
                ease: "easeInOut",
                delay: 0.5,
              },
            }}
            viewport={{ once: true }}
            className="max-w-3xl"
          >
            Inferatos NFT`&apos;`s are a collection of digital artworks
            (NFT`&apos;`s) running on the Polygon network. This website is only
            an interface allowing participants to exchange digital collectibles.
            Users are entirely responsible for the safety and management of
            their own private wallets and validating all transactions and
            contracts generated by this website before approval. Furthermore, as
            the Inferatos smart contracts runs on the Polygon network, there is
            no ability to undo, reverse, or restore any transactions.
            <br />
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving Inferatos`&apos;` digital collectibles.
          </motion.h4>
          <h2>Ownership</h2>
          <motion.h4
            initial={{ opacity: 0, y: -10 }}
            whileInView={{
              opacity: 1,
              y: 0,
              transition: {
                duration: 0.4,
                ease: "easeInOut",
                delay: 0.8,
              },
            }}
            viewport={{ once: true }}
            className="max-w-3xl"
          >
            i. You own the NFT. Inferatos is an NFT on the Polygon blockchain.
            When you purchase an NFT, you own the underlying Inferatos Mask, the
            smartcontract, the “Art”, completely. Ownership of the NFT is
            mediated entirely by the Smart Contract and the Polygon Network: at
            no point may we seize, freeze, or otherwise modify the ownership of
            any Inferatos NFT. ii. Personal Use. Subject to your continued
            compliance with these Terms, INF Group AS grants you a worldwide,
            royalty-free license to use, copy, and display the purchased Art,
            along with any extensions that you choose to create or use, solely
            for the following purposes: (i) for your own personal,
            non-commercial use; (ii) as part of a marketplace that permits the
            purchase and sale of your Inferatos Mask / NFT, provided that the
            marketplace cryptographically verifies each Inferatos Mask
            owner`&apos;`s rights to display the Art for their Inferatos Mask to
            ensure that only the actual owner can display the Art; or (iii) as
            part of a third party website or application that permits the
            inclusion, involvement, or participation of your Inferatos Mask,
            provided that the website/application cryptographically verifies
            each Inferatos Mask owner`&apos;`s rights to display the Art for
            their Inferatos Mask to ensure that only the actual owner can
            display the Art, and provided that the Art is no longer visible once
            the owner of the Inferatos Mask leaves the website/application. iii.
            Commercial Use. Subject to your continued compliance with these
            Terms, INF Group AS grants you an unlimited, worldwide license to
            use, copy, and display the purchased Art for the purpose of creating
            derivative works based upon the Art (“Commercial Use”). Examples of
            such Commercial Use would e.g. be the use of the Art to produce and
            sell merchandise products (T-Shirts etc.) displaying copies of the
            Art. For the sake of clarity, nothing in this Section will be deemed
            to restrict you from (i) owning or operating a marketplace that
            permits the use and sale of Inferatos Masks generally, provided that
            the marketplace cryptographically verifies each Inferatos Mask
            owner`&apos;`s rights to display the Art for their Inferatos Mask to
            ensure that only the actual owner can display the Art; (ii) owning
            or operating a third party website or application that permits the
            inclusion, involvement, or participation of Inferatos Mask
            generally, provided that the third party website or application
            cryptographically verifies each Inferatos Mask owner`&apos;`s rights
            to display the Art for their Inferatos Mask to ensure that only the
            actual owner can display the Art, and provided that the Art is no
            longer visible once the owner of the purchased Inferatos Mask leaves
            the website/application; or (iii) earning revenue from any of the
            foregoing.
          </motion.h4>
        </div>
      </div>
      <div className="mb-28 px-6">
        <CommunityBanner />
      </div>
      <Footer />
    </>
  );
}
